#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your
# load-balancer IP (lb-01).

dom=("www" "lb-01" "web-01" "web-02")

get_and_print ()
{
    output=$(dig @8.8.8.8 "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "The subdomain $2 is a $(echo "$output" | awk '{print $4}') record and points to $(echo "$output" | awk '{print $5}')"
}

if [ -z "$1" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

if [ -z "$2" ]; then
    for str in "${dom[@]}"; do
        get_and_print "$1" "$str"
    done
else
    get_and_print "$1" "$2"
fi

