#!/usr/bin/env bash
# This script installs and Configures an Nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
