#!/usr/bin/env bash
# This script installs and Configures an Nginx server
apt update -y
apt install -y nginx

echo "Hell World!" > /var/www/html/index.html

LINE="\\\trewrite ^/redirect_me https://github.com/Goldjay permanent;"
sed -i "24i $LINE" /etc/nginx/sites-available/default

service nginx restart

