#!/usr/bin/env bash
#Install, update package list and configure HAProxy

sudo apt update
sudo apt install haproxy -y
haproxy=/etc/default/haproxy
echo "ENABLED=1" | sudo tee -a $haproxy

# Configure haproxy to distribute request using roundrobin algorithm
echo 'global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon


defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend manage_entry
	  bind *:80
	  default_backend my_web_servers
backend my_web_servers
	balance static-rr
	server web-01 54.88.199.223:80 check
	server web-02 54.208.92.253:80 check
' >> /etc/haproxy/haproxy.cfg

# Start Haproxy service
sudo systemctl start haproxy.service
