#!/usr/bin/env bash
# Run Nginx as Nginx 
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start

